server:
  port: 8760

eureka:
  instance:
    hostname: server2
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: eurka-server2